### ISSUE TITLE
Missing sites-available folder

### ISSUE THREAD

**Issue by sskorol** [V3ckt0r/docker-httpd-proxy#1]
Hi @V3ckt0r ,

Your Dockerfile uses COPY command against `sites-available` folder. However, it's missing in this project.

I did tried to use these configs to build my own image with custom domain name (for only single site). But instead of provided `index.html`, there was displayed a common httpd welcome screen on 80 port.

But when I pulled already built image, it seems to be working fine.

Could you double check your configs please? I'm struggling for 2 days trying to raise apache with custom `httpd.conf` and `virtual hosts`, but have no luck yet. However, it works perfect on Windows. Not sure what I'm missing.

**Comment by V3ckt0r** [comment]
Hey @sskorol,

Thanks for getting in touch. I have added the sites-available folder into the project, docker will now build the container fully. 
In regards to your particular issue, could you show me your dockerfile and related apache files. Alternatively put your docker image on dockerhub and send me the link. I can download it and have a look at why your index is not getting rendered.

Thanks
